{
    "name": "Hospital Management System",
    "author": "Jason Nohea",
    "website": "https://www.testonly.test",
    "summary": "Odoo 16 Development",
    "depends": ["mail", "web"],
    "license": "AGPL-3",
    "data": [
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/server_action.xml",
        "views/menu.xml",
        "views/patient.xml",
        "views/rooms.xml",
        "views/clinicaction.xml",
        "views/nurse.xml",
        "views/equipmentusage.xml",
        "views/frontoffice.xml",
        "views/equipment.xml",
        "views/medicalcheck.xml",
        "views/docinspect.xml",
        # "views/clinicservices.xml",
        "views/clinicpayment.xml",
        "views/doctor.xml",
        "reports/patient_card.xml",
        "reports/report.xml",
    ],
}
