from . import patient
from . import medicalcheck
from . import docexamine
from . import clinicservices
from . import clinicpayment
from . import doctor
from . import nurse
from . import rooms
from . import clinicaction
from . import equipment
from . import frontoffice
from . import equsage
from . import actionlog
